layout_spectrum: 0.2744361
color:
  saturation: 0.0925303
  lightness: 0.5826174
  brandStrength: 0.3566697
  brandColors:
    - '#FFFFFF'
    - '#5E4523'
    - '#8F7F6F'
    - '#AFA494'
    - '#CFC6B9'
  rhythmicContrast: 0.5036007
typography_spectrum: 0.2957394
name: Paula Meinberg
